### ISSUE TITLE
How to use it ? I'm a noob actually can you help me ?

### ISSUE THREAD

**Issue by xoxxxoooxoxo** [Gameye98/SpazSMS#1]
So i installed it and opened it 
It showed usual readme,  licence etc etc options. There were some options like jdid, phd, lite, tri. I opened them too and the code loaded but i don't know how to use it.
Ex :- phd says usage :- phd.py PHONE 
So what should i type next ? What command ?

**Comment by KingVik1** [comment]
python2 phd.py 00000000000.
